apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esw-rtmp
  labels:
    deployment: esw-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: esw-rtmp
  template:
    metadata:
      labels:
        pod: esw-rtmp
    spec:
      containers:
        - name: esw-rtmp
          image: sb/esw-rtmp-server
          imagePullPolicy: Always
          ports:
            - name: rtmp-port
              containerPort: 1935
            - name: http-port
              containerPort: 80
